"""create projects table

Revision ID: 3408de26aa9a
Revises: 
Create Date: 2026-06-19 15:26:20.298657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3408de26aa9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Project title'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='Unique URL identifier'),
    sa.Column('description', sa.Text(), nullable=True, comment='Short description'),
    sa.Column('full_description', sa.Text(), nullable=True, comment='Full project description'),
    sa.Column('project_type', sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'OFFICE', 'VILLA', 'CULTURAL', 'EDUCATIONAL', 'OTHER', name='projecttype'), nullable=True, comment='Type of project'),
    sa.Column('client_name', sa.String(length=255), nullable=True, comment='Client name'),
    sa.Column('year', sa.String(length=20), nullable=True, comment='Project year'),
    sa.Column('area', sa.String(length=50), nullable=True, comment='Area in square meters'),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='projectstatus'), nullable=False, comment='Publication status'),
    sa.Column('cover_image', sa.String(length=500), nullable=True, comment='Cover image URL'),
    sa.Column('gallery_images', sa.String(length=500), nullable=True, comment='Gallery image URLs (comma-separated)'),
    sa.Column('is_featured', sa.Boolean(), nullable=False, comment='Show in featured section'),
    sa.Column('views', sa.Integer(), nullable=False, comment='View count'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
