"""empty message

Revision ID: 4772d5a0e321
Revises: 0cec3e26217b
Create Date: 2026-06-27 15:23:20.762179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4772d5a0e321'
down_revision: Union[str, None] = '0cec3e26217b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'title',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=255),
               comment='عنوان پروژه',
               existing_comment="Multilingual title: {'en': '...', 'fa': '...'}",
               existing_nullable=False)
    op.alter_column('projects', 'description',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               comment='توضیحات کوتاه',
               existing_comment="Multilingual short description: {'en': '...', 'fa': '...'}",
               existing_nullable=True)
    op.alter_column('projects', 'full_description',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               comment='توضیحات کامل',
               existing_comment="Multilingual full description: {'en': '...', 'fa': '...'}",
               existing_nullable=True)
    op.alter_column('projects', 'features',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               comment='ویژگی\u200cها (جداسازی با کاما)',
               existing_comment="Multilingual features: {'en': ['feat1', 'feat2'], 'fa': ['...']}",
               existing_nullable=True)
    op.alter_column('projects', 'project_type',
               existing_type=postgresql.ENUM('RESIDENTIAL', 'COMMERCIAL', 'OFFICE', 'VILLA', 'CULTURAL', 'EDUCATIONAL', 'OTHER', name='projecttype'),
               comment=None,
               existing_comment='Type of project',
               existing_nullable=True)
    op.alter_column('projects', 'client_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Client name',
               existing_nullable=True)
    op.alter_column('projects', 'year',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Project year',
               existing_nullable=True)
    op.alter_column('projects', 'area',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Area in square meters',
               existing_nullable=True)
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', name='projectstatus'),
               comment=None,
               existing_comment='Publication status',
               existing_nullable=False)
    op.alter_column('projects', 'cover_image',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Cover image URL',
               existing_nullable=True)
    op.alter_column('projects', 'gallery_images',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Gallery image URLs (comma-separated)',
               existing_nullable=True)
    op.alter_column('projects', 'is_featured',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Show in featured section',
               existing_nullable=False)
    op.alter_column('projects', 'views',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='View count',
               existing_nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_projects_slug', table_name='projects', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Unique URL identifier'))
    op.create_index('ix_projects_slug', 'projects', ['slug'], unique=True)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'views',
               existing_type=sa.INTEGER(),
               comment='View count',
               existing_nullable=False)
    op.alter_column('projects', 'is_featured',
               existing_type=sa.BOOLEAN(),
               comment='Show in featured section',
               existing_nullable=False)
    op.alter_column('projects', 'gallery_images',
               existing_type=sa.VARCHAR(length=500),
               comment='Gallery image URLs (comma-separated)',
               existing_nullable=True)
    op.alter_column('projects', 'cover_image',
               existing_type=sa.VARCHAR(length=500),
               comment='Cover image URL',
               existing_nullable=True)
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', name='projectstatus'),
               comment='Publication status',
               existing_nullable=False)
    op.alter_column('projects', 'area',
               existing_type=sa.VARCHAR(length=50),
               comment='Area in square meters',
               existing_nullable=True)
    op.alter_column('projects', 'year',
               existing_type=sa.VARCHAR(length=20),
               comment='Project year',
               existing_nullable=True)
    op.alter_column('projects', 'client_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Client name',
               existing_nullable=True)
    op.alter_column('projects', 'project_type',
               existing_type=postgresql.ENUM('RESIDENTIAL', 'COMMERCIAL', 'OFFICE', 'VILLA', 'CULTURAL', 'EDUCATIONAL', 'OTHER', name='projecttype'),
               comment='Type of project',
               existing_nullable=True)
    op.alter_column('projects', 'features',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               comment="Multilingual features: {'en': ['feat1', 'feat2'], 'fa': ['...']}",
               existing_comment='ویژگی\u200cها (جداسازی با کاما)',
               existing_nullable=True)
    op.alter_column('projects', 'full_description',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               comment="Multilingual full description: {'en': '...', 'fa': '...'}",
               existing_comment='توضیحات کامل',
               existing_nullable=True)
    op.alter_column('projects', 'description',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               comment="Multilingual short description: {'en': '...', 'fa': '...'}",
               existing_comment='توضیحات کوتاه',
               existing_nullable=True)
    op.alter_column('projects', 'title',
               existing_type=sa.String(length=255),
               type_=postgresql.JSON(astext_type=sa.Text()),
               comment="Multilingual title: {'en': '...', 'fa': '...'}",
               existing_comment='عنوان پروژه',
               existing_nullable=False)
    # ### end Alembic commands ###
